# Generated by Django 2.2.4 on 2019-08-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190812_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='images/'),
        ),
    ]
